version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nexaquanta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "
      python -m alembic upgrade head &&
      cd app &&
      python main.py
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443" # Uncomment if you configure HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web


volumes:
  postgres_data: